site_name: Лабораторная работа №1. Зотов Леонид. K33392
site_url: https://lab1docs.com
nav:
  - Задание 1: task1.md
  - Задание 2: task2.md
  - Задание 3: task3.md
  - Задание 4: task4.md
  - Задание 5: task5.md
